# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCli < Formula
  desc "note-cli is a CLI command tool for creating, writing, and managing note articles"
  homepage "https://github.com/JY8752/note-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JY8752/note-cli/releases/download/v0.5.0/note-cli_Darwin_x86_64.tar.gz"
      sha256 "417bf1dc130d319f69ae24adadffd90b64c8ebd008c78cee0a4f57de7720f618"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JY8752/note-cli/releases/download/v0.5.0/note-cli_Darwin_arm64.tar.gz"
      sha256 "a5c9107d12720f2f624c4a9bbd764fca681b546cf0a2e16f9c32f7bc86a74092"

      def install
        bin.install "note-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JY8752/note-cli/releases/download/v0.5.0/note-cli_Linux_arm64.tar.gz"
      sha256 "e49ad8c4449d75e6b891f24964fa2144ccaac95ad2669819f0d5d3c7bae51a75"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JY8752/note-cli/releases/download/v0.5.0/note-cli_Linux_x86_64.tar.gz"
      sha256 "f0bc6da66f93785ee2fb5ce98aad917620b6a933e66c545797fa478eb0f42704"

      def install
        bin.install "note-cli"
      end
    end
  end
end
