# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCli < Formula
  desc "note-cli is a CLI command tool for creating, writing, and managing note articles"
  homepage "https://github.com/JY8752/note-cli"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JY8752/note-cli/releases/download/v0.7.0/note-cli_Darwin_x86_64.tar.gz"
      sha256 "9edaf33c156e2cb236b5554a081ebe1b5e1063738db23ad08e027d6c3ee44fd3"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JY8752/note-cli/releases/download/v0.7.0/note-cli_Darwin_arm64.tar.gz"
      sha256 "da913136d0148449d18a5d11dab18a7a3db95d51c18ff87ab910206c5ae8ab5d"

      def install
        bin.install "note-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JY8752/note-cli/releases/download/v0.7.0/note-cli_Linux_x86_64.tar.gz"
      sha256 "e2c39fd08f36908535db76ed0f82d8534d1139056bd6db184a820fb39736b3ca"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JY8752/note-cli/releases/download/v0.7.0/note-cli_Linux_arm64.tar.gz"
      sha256 "aecb826f78332638572a15174c416abf4c26d7fde51ad9c7a1d65f8f13a5c355"

      def install
        bin.install "note-cli"
      end
    end
  end
end
